Memory home page
Stevens-ReCollect/ReCollect pull request #23
Opened 2021-11-05 13:44 UTC by LDomadia

- Add new moment button (photo, video, audio) to the memory
- Added reorderable list for moments
- [ ] need to change style of the list
- [ ] need to add picture and caption if there's no moments in the memory

2021-11-07 20:13 UTC, sboamah requested changes
Some spelling errors in the hint text of the create memory form ("Desciption", "MM/DD/YYY") but other than that, the flow is great.

2021-11-07 20:48 UTC, LDomadia commented
Spelling errors have been fixed

2021-11-08 01:13 UTC, Jhector10 approved these changes

2021-11-08 12:20 UTC, kushal1223 approved these changes

2021-11-08 20:31 UTC, sboamah approved these changes

2021-11-08 22:07 UTC, merged