Issue #68 - sign up error checking
Stevens-ReCollect/ReCollect pull request #72
Opened 2022-01-06 19:15 UTC by LDomadia

closes #68

2022-01-07 16:46 UTC, Mathieu-Nagle approved these changes

2022-01-09 19:18 UTC, Jhector10 requested changes
You can check my branch "new-signin" to see the validators that I created for that one to see which one would be best fit for our app. We can discuss more in the standup

2022-01-15 01:27 UTC, kushal1223 approved these changes

2022-01-15 17:10 UTC, Jhector10 approved these changes

2022-01-15 17:36 UTC, merged